### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by Sq-CC** [Ed1s0nZ/banana_blackmail#1]
main.go:4:2: no required module provides package github.com/ed11s00n/blackmail/Delete_VSSADMIN: go.mod file not found in current directory or any parent directory; see 'go help modules'
main.go:5:2: no required module provides package github.com/ed11s00n/blackmail/Directory_traversal: go.mod file not found in current directory or any parent directory; see 'go help modules'

**Comment by Liam929** [comment]
@Oldman19 Have you already solve this issue as you showed?I would appreciate it if you could do me a favor.

**Comment by Ed1s0nZ** [comment]
编译前执行以下两条命令：
go mod init xxx
go mod tidy

然后再执行编译命令：
go build
